name: Build .NET Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Restore dependencies
        run: dotnet restore ./src

      - name: Build
        run: dotnet build ./src --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/LxInterview.Api/LxInterview.Api.csproj --configuration Release --output ./publish --no-build

      - name: Archive production artifacts
        run: tar -czvf app.tar.gz -C ./publish .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-artifacts
          path: app.tar.gz

      - name: Deploy to DigitalOcean Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@170.64.218.87 << 'EOF'
           mkdir -p /var/www/myapp
           tar -xzvf /root/app.tar.gz -C /var/www/myapp
           rm /root/app.tar.gz

           # Kill any existing .NET application running
           pkill dotnet || true

           # Run the new .NET application
           dotnet /var/www/myapp/LxInterview.Api.dll &
           EOF
